# -- Number of replicas.
replicaCount: 1

additionalVolumeMounts: []

additionalVolumes: []

affinity: {}

autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80

fullnameOverride: ""

image:
  # -- Image Pull Policy.
  pullPolicy: IfNotPresent
  # -- Image Registry.
  repository: ghcr.io
  # -- Image Repository.
  repository: hascheksolutions/pictshare
  # -- Image Tag.
  tag: 2.0.1

imagePullSecrets: []

livenessProbe:
  httpGet:
    path: /int/upload
    port: http
readinessProbe:
  httpGet:
    path: /int/upload
    port: http

nameOverride: ""

nodeSelector: {}

persistence:
  data:
    # -- Storage PVC Access Modes.
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        # -- Storage PVC Size.
        storage: 1Gi
    # -- Storage Class to use for uploads storage.
    storageClassName:

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

resources: {}

securityContext: {}

service:
  port: 80
  # -- Service Type.
  type: ClusterIP

serviceAccount:
  annotations: {}
  automount: true
  create: false
  name: ""

tolerations: []

ingress:
  # -- Whether to use an Ingress for application access.
  enabled: false
  # annotations: {}
  # className: nginx
  hosts: []
  tls: []

uploadIngress:
  # -- Whether to use a separate Ingress for uploading.
  enabled: false
  annotations: {}
  # className: nginx
  hosts: []
  tls: []
